name: mdn_nca
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.0
  - torchvision=0.20.1
  - typing_extensions=4.11.0
  - tzdata=2024b
  - urllib3=2.2.3
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - numpy=2.0.1
  - pytorch=2.5.1
  - matplotlib=3.9.2
  - freetype=2.12.1
  - libwebp=1.3.2
  - markupsafe=2.1.3
  - pyparsing=3.2.0
  - jinja2=3.1.4
  - python-dateutil=2.9.0
  - requests=2.32.3
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.13.2
  - tk=8.6.14
  - pip=24.2
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - filelock=3.13.1
  - cycler=0.12.1
  - lz4-c=1.9.4
